apiVersion: kubeflow.org/v1beta1
kind: WorkspaceKind
metadata:
  name: jupyter-lab
spec:
  podTemplate:
    httpProxy:
      removePathPrefix: false
      requestHeaders: {}
    options:
      imageConfig:
        default: "jupyter_scipy_171"
        values:

          ## ================================
          ## EXAMPLE 1: a hidden option
          ## ================================
          - id: "jupyter_scipy_170"
            spawner:
              displayName: "jupyter-scipy:v1.7.0"
              description: "JupyterLab 1.7.0, with SciPy Packages"
              hidden: true
            redirect:
              to: "jupyter_scipy_171"
              waitForRestart: true
            spec:
              ## the container image to use
              ##
              image: "docker.io/kubeflownotebookswg/jupyter-scipy:v1.7.0"

              ## ports that the container listens on
              ##  - currently, only HTTP is supported for `protocol`
              ##  - currently, all ports use the same `httpProxy` settings
              ##  - if multiple ports are defined, the user will see multiple "Connect" buttons
              ##    in a dropdown menu on the Workspace overview page
              ##
              ports:
                - displayName: "JupyterLab"
                  port: 8888
                  protocol: "HTTP"
                - displayName: "JupyterLab2"
                  port: 9999
                  protocol: "HTTP"

          ## ================================
          ## EXAMPLE 2: a visible option
          ## ================================
          - id: "jupyter_scipy_171"
            spawner:
              displayName: "jupyter-scipy:v1.7.1"
              description: "JupyterLab 1.7.1, with SciPy Packages"
              hidden: false
            redirect:
              to: "jupyter_scipy_171"
              waitForRestart: true
            spec:
              image: "kubeflownotebookswg/jupyter-scipy:v1.8.0"
              ports:
                - displayName: "JupyterLab"
                  port: 8888
                  protocol: "HTTP"
      podConfig:
        default: "small_gpu"
        values:
          - id: "small_gpu"
            redirect:
              to: ""
              waitForRestart: false
            spawner:
              description: "test"
              displayName: "test"
              hidden: false
            spec:
              affinity: {}
              resources:
                requests:
                  memory: "64Mi"
                limits:
                  cpu: "500m"
    podMetadata:
      annotations: {
        "version": "v2.0"
      }
      labels: {}
    probes:
      startupProbe:
      livenessProbe:
      readinessProbe:
    extraEnv:
      - name: "NB_PREFIX"
        value: "{{ .PathPrefix }}"
    serviceAccount:
      name: "default"
    volumeMounts:
      home: "/home/jovyan"
  spawner:
    deprecated: false
    deprecationMessage: "test"
    description: "test"
    displayName: "test"
    hidden: false
    icon:
      url: "image"
    logo:
      url: "image"
